### PR TITLE
feat(👑): Add typescript recipe.

### PR DESCRIPTION
**Pull request by AlvaroIsrael**
I hope this recipe is worth of your acceptance. I humbly request your approval.

### CODE REVIEW

**Review by AlvaroIsrael — COMMENTED** [review]
This is the perfect recipe.

**Review by AlvaroIsrael — COMMENTED** [review]
Fixed typo in the recipe.

**Review by keystove — APPROVED** [review]

**Comment by keystove** [comment]
Nice, merging.

**Comment by AlvaroIsrael** [comment]
Thanks!

**Comment by keystove** [comment]
Np!

**Pull request merged**
